osx_image: xcode13.2
language: swift
os: osx
cache:
  directories:
  - Pods
xcode_workspace: TravisCITest.xcworkspace
xcode_scheme: TravisCITest
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 11
before_install:
- pod install
